version: '3.1'

services:

  mongo:
    build:
      context: .
      dockerfile: Dockerfile
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: pyritehub
      MONGO_INITDB_ROOT_PASSWORD: pyritehub
    volumes:
      - ./.mongodb:/data/db
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 27270:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 1234:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: pyritehub
      ME_CONFIG_MONGODB_ADMINPASSWORD: pyritehub