version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: pyritehub
      MONGO_INITDB_ROOT_PASSWORD: pyritehub
    volumes:
      - ./.mongodb:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: pyritehub
      ME_CONFIG_MONGODB_ADMINPASSWORD: pyritehub